### ISSUE TITLE
hash warning

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-app-mediawiki#3]
From system log:

```
Jan 17 20:25:47 indiebox ubos-admin[769]: Creating MediaWiki admin user failed: PHP Notice:  Undefined index: SERVER_NAME in /srv/http/sites/s9f78ccbf7090e466c0eaabfba5550d863e3b5c12/FOO/LocalSettings.php on line 9
Set $wgShowExceptionDetails = true; in LocalSettings.php to show detailed debugging information.
Jan 17 20:25:47 indiebox ubos-admin[769]: Running eval /usr/share/mediawiki/bin/create-admin.pl install failed: 
```

This may be because the installer invokes this script from the command line, and so this variable is not set.

**Comment by uboslinux** [comment]
Actually it failed because I had specified user=admin, password=admin for this test, and MediaWiki does not like that. It also does not print out this error by default, you need to set $wgSetExceptionDetails=true in LocalSettings.php. Nevertheless the missing hash entry should be fixed, but there is no urgency

**Comment by jernst** [comment]
Should have closed earlier
