### ISSUE TITLE
https * install accessed at IP address references CSS at http, does not resolve

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-app-mediawiki#6]
Enter in browser: https://192.168.56.101/
will contain

```
<link rel="stylesheet" href="http://192.168.56.101/foo...
```

instead of https. Also, referencing those links (automatic redirect to https is okay) produces content:

```
/*
Problematic modules:   {"mediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.ui.button%7    Cskins.vector.styles":"missing"}
*/
```

**Comment by jernst** [comment]
This seems to work for a non-tls site, but not for a tls site, regardless of whether \* or a hostname was given.
